name: ci

on:
  pull_request:
  push:
    branches: [main]

jobs:
  validate:
    name: fmt & validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.9.*"

      - name: terraform fmt
        run: terraform fmt -check -recursive -diff

      - name: terraform init (module)
        run: terraform init -backend=false

      - name: terraform validate (module)
        run: terraform validate

      - name: terraform validate (examples)
        working-directory: examples
        run: |
          terraform init -backend=false
          terraform validate

  lint:
    name: tflint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: terraform-linters/setup-tflint@v4
        with:
          tflint_version: latest

      - run: tflint --init
      - run: tflint --recursive --format compact

  security:
    name: trivy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Trivy config scan
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: config
          scan-ref: .
          exit-code: "1"
          severity: HIGH,CRITICAL
